install:
 - cinst pester

version: 1.0.0.{build}
build_script:
 - ps: New-ModuleManifest -ModuleVersion $ENV:APPVEYOR_BUILD_VERSION -path .\RollingRestart.psd1 -Author 'Paul Kelly' -Company 'PK Services' -Description 'Restart independent servers in parallel and dependent servers in sequence.' -RootModule '.\RollingRestart.psm1'

test_script:
 - ps: $Results = Invoke-Pester -Path ".\" -OutputFOrmat NUnitXml -OutputFile TestResults.xml -PassThru
 - ps: (New-Object 'System.Net.WebClient').UploadFile("https://ci.appveyor.com/api/testresults/nunit/$($ENV:APPVEYOR_JOB_ID)", (Resolve-Path .\TestResults.xml))
 - ps: if ($Results.FailedCount -gt 0) { throw "$($Results.FailedCount) tests failed."}

environment:
  auth_token:
    secure: qxWzUSaaQl25L9cXR7aoBReIP6X6jaELEGrJb39BZKV5324aUEopxuktIT7XFHT9
    
deploy:
  release: myproduct-v$(appveyor_build_version)
  description: 'Release description'
  provider: GitHub
  auth_token:
    secure: $env:authtoken
  draft: false
  prerelease: false
  on:
    branch: master                 # release from master branch only
    appveyor_repo_tag: false        # deploy on tag push only
